version: "3.9"

services:
  telegram-abacus-mem-bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=UTC
    # Если нужно, раскомментируй том для горячей перезагрузки кода
    # volumes:
    #   - .:/app

